### ISSUE TITLE
[Feature Proposal] Inline form in <nav> with text input

### ISSUE THREAD

**Issue by schicho** [kevquirk/simple.css#166]
# Proposal
Usually one may want a search box in the navigation bar. However simply using a form introduces a line break. Additionally the padding and line height is off.

I propose additional rules to allow for a proper inline search box.

```css
header > nav form {
  display: inline;
  margin: 0;
  padding: 0;
}

header > nav input[type="text"] {
  font-size: inherit;
  line-height: inherit;
  margin: 0 0.5rem 1rem 0.5rem;
  padding: 0.1rem 1rem;
}
```
Before:
![image](https://github.com/kevquirk/simple.css/assets/64368773/2a8fe1f5-5592-4274-9b4f-739b695ac6a8)

After:
![image](https://github.com/kevquirk/simple.css/assets/64368773/372b0143-0a81-48b9-b116-e7a98c7c1ce7)

Using this HTML:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Simple CSS Test</title>
    <link rel="stylesheet" href="simple.css">
</head>

<body>
    <header>
        <nav>
            <a href="/">Home</a>
            <a href="/about">About</a>
            <form><input type="text" placeholder="Search"></form>
            <a href="/contact">Contact</a>
        </nav>
        <h1>Simple CSS Test</h1>
    </header>
    <main>
        <p> Lorem ipsum dolor sit amet. </p>
    </main>
</body>
</html>
```

# Considerations

Is this a worth while idea or should I manually do this every time?
Will others also use this? Will this break simple.css for others?

I attempted to be as minimal as possible with my css rules.
If you consider this reasonable, I can open a PR.
