### ISSUE TITLE
Footer does not always go at the bottom of the screen

### ISSUE THREAD

**Issue by adamkpickering** [kevquirk/simple.css#206]
I tried using simple.css for my website, but I have a number of pages where the content is quite short. The result is that the footer has a bunch of space below it - this looks weird. Ideally, the footer would go only at the bottom of the page, and there would be white space between the end of the content and the footer. Here is some example HTML:

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
</head>

<body>
  <header>This is the header</header>
  <main>here is a short body</main>
  <footer>This is the footer</footer>
</body>

</html>
```

And what the browser renders with this HTML:

![image](https://github.com/user-attachments/assets/d9823c06-9fab-4888-8e80-e379e3072f8b)

Any chance we can ensure the footer is always at the bottom? Or did I miss something?

**Comment by lkhrs** [comment]
@adamkpickering I merged #209 to fix this issue, but this change broke sites with presentational elements directly under `<body>` (see PR for breakdown) and we decided to revert. You can use the following code to achieve this for your project:

```css
html, body {
	height: 100%;
}
body {
	grid-template-rows: min-content 1fr auto;
}
/* Optional: Make footer padding consistent */
body > footer {
	padding: 2rem 1rem;
}
```

**Comment by adamkpickering** [comment]
Thanks for the help @lkhrs. I tried it out, and it didn't seem to work on my site... and then I forgot to mention that here. So it's probably best that the change is reverted.

For what it's worth, I figured out how to do this myself by adding:

```css
body {
    display: flex;
    flex-direction: column;
}

header {
    flex-shrink: 0;
}

main {
    flex-grow: 1;
}

footer {
    flex-shrink: 0;
}
```
