### ISSUE TITLE
@media print

### ISSUE THREAD

**Issue by timotheegoguely** [kevquirk/simple.css#219]
Hello, 

I'd like to suggest adding the followings lines of CSS to make `simple.css` printer-friendly.
Feel free to improve it if you want!

```css
@media print {
  @page {
    margin: 1cm;
  }
  *:not(input, select) {
    background: none !important;
  }
  body {
    display: block;
  }
  body > header nav,
  body > footer,
  a[href^="#fn"] {
    display: none;
  }
  a[href^="http"]::after {
    content: " <" attr(href) ">";
  }
  abbr[title]:after {
    content: " (" attr(title) ")";
  }
  a {
    text-decoration: none;
  }
  p {
    widows: 3;
    orphans: 3;
  }
  hr {
    border-top: 1px solid var(--border);
  }
  mark {
    border: 1px solid var(--border);
  }
  pre, table, figure, img, svg {
    break-inside: avoid;
  }
  pre code {
    white-space: pre-wrap;
  }
  button, .button {
    color: var(--text) !important;
  }
}
```
