### ISSUE TITLE
Set background colour for entire page width in body section

### ISSUE THREAD

**Issue by tastapod** [kevquirk/simple.css#234]
I want to set the background colour for the entire page width _for a section_ in the `body`, like you do with the main `header`. The thing is, you have the body constrained to column 2 of 3, so I can't see a way to say 'ignore that this is a grid cell, just style the whole width!'

I can see that you have used `grid-column: 1 / -1;` to make the main header full-width, but this doesn't seem to work for me. I am a few levels down, in a `body > main > content > div`, and even if I cascade the `layout: grid` with `grid-column-template: subgrid` at each level, it doesn't seem to affect anything.

Am I missing something, or is there some affordance I need in `simple.css` (maybe labelled columns?) to pull this off?

[Edit: emphasise that this is just for a single section within the page.]

**Comment by lkhrs** [comment]
I think @tastapod wants to make a single section full width, not the whole page.

One important thing about subgrid is that it inherits the tracks available to the element. In our case, `<main>` was given one track via `grid-column: 2;`. Trying to set `grid-column: 1 / -1;` on a child of `main` results in the child taking up all the space from the beginning of track 1 to the end of track 1.

A workaround would look like this:
```css
main {
    display: grid;
    /* Inherit the grid-column tracks available */
    grid-template-columns: subgrid;
    /* Take up all available columns for its row */
    /* Overrides body > * {grid-column: 2;} */
    grid-column: 1 / -1;
}

main > * {
    /* Make all direct children use column 2 */
    grid-column: 2;
}

/* Use this class on a direct child of <main> to set full width */
.fullwidth {
    grid-column: 1 / -1;
}
```

With the following markup layout:
```html
<body>
    <main>
        <!-- Normal width (track 2) -->
        <section></section
        <!-- Full width (all available tracks) -->
        <section class="fullwidth"></section>
        <!-- Normal width (track 2) -->
        <section></section>
    </main>
</body>
```

**Comment by tastapod** [comment]
Yes, @lkhrs is correct. I'm trying to make the background for each `<section>` in a page different colours—either alternating or cycling through several colours, I haven't decided yet—going right across the page.

I tried the `subgrid` / `grid-column` trick and it didn't work. I'm a couple of levels down by the time I get to the section I want to style—typically `body>main>content>section`, say—so I tried cascading the grid through all of these and it didn't work. Perhaps I missed something, I can try again tomorrow. At least I know I'm on the right lines!

Is there anything you can do in `simple.css` to make this easier, or is it just a question of me wrangling grid columns until it works? (I'm new to grid layouts!) I saw something about naming columns and column ranges, but I don't know that that will necessarily help here either.

**Comment by kevquirk** [comment]
Sorry, I misunderstood.

**Comment by lkhrs** [comment]
> I tried the subgrid / grid-column trick and it didn't work. I'm a couple of levels down by the time I get to the section I want to style—typically body>main>content>section, say—so I tried cascading the grid through all of these and it didn't work. Perhaps I missed something, I can try again tomorrow. At least I know I'm on the right lines!

I am curious as to the reasoning behind the `<content>` custom element here. If you're trying to represent a content area, `<main>` is the intended element for that. Is `<content>` a web component? Maybe you're fighting an extra level of nesting you don't need.

If you do need `<content>` though, here's the updated custom CSS:

```css
main,
content,
.fullwidth {
    display: grid;
    grid-template-columns: subgrid;
    grid-column: 1 / -1;
}

content > *,
.fullwidth > * {
    grid-column: 2;
}
```

Example layout:
```html
<body>
    <main>
        <content>
            <!-- Normal width (track 2) -->
            <section></section
            <!-- Full width (all available tracks) -->
            <section class="fullwidth">
                <p>I'm aligned to column 2 while my parent uses all 3 columns!</p>
            </section>
            <!-- Normal width (track 2) -->
            <section></section>
        </content>
    </main>
</body>
```

> Is there anything you can do in simple.css to make this easier, or is it just a question of me wrangling grid columns until it works? (I'm new to grid layouts!) I saw something about naming columns and column ranges, but I don't know that that will necessarily help here either.

We use three columns with column 2 being the content area. We could name column 2 to "Middle column" and the `1 / -1` range to "Full width", but it won't functionally change.

I'm also hesitant to add the code to allow for full width breakouts in `<main>`. I'm not sure how much breakage switching the layout mode to grid will cause. Maybe something to consider for the next major version.

**Comment by tastapod** [comment]
I ended up with this rather neat solution, based on your example:

```css
.grid-cascade {
    display: grid;
    grid-template-columns: surged;

    /* cascaded nodes are full-width */
    grid-column: 1/ -1;

    > :not(.grid-cascade) {
        /* non-cascading children use the centre column */
        grid-column: 2;
    }
}
```

So I can cascade the full width wherever I need to, just by setting `class="grid-cascade"` on the intermediate nodes. I don't need a separate `fullwidth` class, because that is the default on a grid-cascading child node.

In this case, it's a Hugo theme where I have a `<body>` with `<content>` made up of a bunch of section blocks as shortcodes.

In the section shortcode, I surround everything with a `<div class="grid-cascade">` so I can style the background as full width, while any child elements are automatically placed in the middle column.  (I would use a `<section>` but I don't want the horizontal border styling. I guess I could just override that in my own `tweaks.css` file.)

Thanks again for your help, it's looking great now! (And still simple enough to fit in my head.)
