### ISSUE TITLE
Cannot make `body > header` under some UI frameworks.

### ISSUE THREAD

**Issue by Gerhut** [kevquirk/simple.css#75]
Hi, thanks for the really convenient project.

As per #31, it's limited that the header style only applied to the direct child of body element. But sometimes we have to put all elements under a "root" `<div>` element. Like React or Vue, the root Component should be mounted to a root element other than body, and the DOM structure would be like:

```html
<div id="root">
  <header><h1>App</h1></header>
</div>
```

So, under these frameworks I cannot apply the header style anymore. I totally understand what #31 is saying but it would be great if we can figure out other kind of `<header>` limitations.

**Comment by kevquirk** [comment]
Apologies for the delay in reply.

But that's not semantic HTML. The whole point of this project is to get away from the overly-convoluted ways these massive frameworks do things.

**Comment by hacknlove** [comment]
Just add this to your custom css:

```css
#__next > header { 
  background: var(--accent-bg);
  border-bottom: 1px solid var(--border);
  text-align: center;
  padding: 0 0.5rem 2rem 0.5rem;
  grid-column: 1 / -1;
  box-sizing: border-box;
}

 #__next > header h1 {
  max-width: 1200px;
  margin: 1rem auto;
}

 #__next > header p {
  max-width: 40rem;
  margin: 1rem auto;
}


#__next > footer {
  margin-top: 4rem;
  padding: 2rem 1rem 1.5rem 1rem;
  color: var(--text-light);
  font-size: 0.9rem;
  text-align: center;
  border-top: 1px solid var(--border);
}
```
