### ISSUE TITLE
Navigation links with icons are not in simple.css or simple-v1.css

### ISSUE THREAD

**Issue by alexspark** [kevquirk/simple.css#79]
I tried to mimic the navigation link with svg icon that the demo employs with the github icon.

```
<nav>
    <a href="github.com">
        <svg class='icon'>
            <path ...>
        </svg>
        "github"
    </a>
</nav>
```

When I inspect the demo, there is a small stylesheet that is for this demo page.

I just copied the styles for .icon into my stylesheet, and for the most part it worked.

```css
.icon {
  vertical-align: sub;
  padding-right: .25rem;
  display: inline-block;
  width: 1em;
  height: 1.3em;
  margin-right: 0.2rem;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}
```

Should this be included in simple.css?
