### ISSUE TITLE
Add definition lists styles

### ISSUE THREAD

**Issue by hikadev** [kevquirk/simple.css#84]
Add definition lists in simple.css

In my custom CSS I add `<dl>`, `<dt>`, `<dd>` styles as:

```css
dl {
  display: grid;
  grid-template-columns: auto 1fr;
}

dl dt {
  grid-column-start: 1;
  color: var(--text-light);
}

dl dd {
  grid-column-start: 2;
}
```
